default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  username: <%= ENV.fetch("DB_USER", "app_perfil") %>
  password: <%= ENV["DB_PASSWORD"] || (Rails.env.production? ? raise("DB_PASSWORD not set") : "dev_password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: app_perfil_development

test:
  <<: *default
  database: app_perfil_test

production:
  <<: *default
  database: app_perfil_production